spring:
  application:
    name: discovery-client
  mvc.view.prefix: /static/
  mvc.view.suffix: .html
server:
  port: 80
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/